---
- name: Drupal | Get the latest stable version(7)
  git:
    repo: "https://github.com/drupal/drupal.git"
    version: "{{ drupal_8_branch }}"
    dest: "{{ drupal_docroot }}"
    depth: 1

# - name: Drupal | Restore if there is a DB snapsot

- name: Drupal | Run composer if we are running D8
  composer:
    command: install
    working_dir: "{{ drupal_docroot }}"
  when: drupal_major_version == 8

- name: Drupal | Check if site is already installed
  command: >
    drush status --root={{ drupal_docroot }}
  register: drush_status

- name: Drupal | Give appropriate permissions for files directory
  file:
    dest: "{{ drupal_docroot }}/sites/default/files"
    recurse: yes
    mode: a+w
  when: not drush_status.stdout | search("Drupal bootstrap\s+:\s+Successful")
    
- name: Drupal | Drush site install if not already installed
  command: >
    drush site-install standard -y
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_account_name }}
    --account-pass={{ drupal_account_pass }}
    --db-url=mysql://{{ drupal_db.user }}:{{ drupal_db.password }}@localhost/{{ drupal_db.name }}
    -r {{ drupal_docroot }}
  when: not drush_status.stdout | search("Drupal bootstrap\s+:\s+Successful")
  notify: "restart {{ webserver }}"
